apiVersion: v1
kind: Secret
type: Opaque
metadata: 
  name: slack-secret
  namespace: monitoring
data:
  slack-webhook-url: "aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA1REI2Uk5EREcvQjA1Q1hDMExKRzcvV3dRV2RlMU80WnJBM2k0eXhPVjBva1d4"